### ISSUE TITLE
Dumped file but file will not be parsed

### ISSUE THREAD

**Issue by trickster0** [helpsystems/nanodump#1]
`INFO:root:Parsing file ../../TEST_1636586596_lsass.dmp
INFO:pypykatz:===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====
INFO:pypykatz:pypyKatz version: 0.3.7
INFO:pypykatz:CPU arch: X64
INFO:pypykatz:OS: Windows 10
INFO:pypykatz:BuildNumber: 22000
INFO:pypykatz:MajorVersion: 6 
INFO:pypykatz:MSV timestamp: 0
INFO:pypykatz:===== BASIC INFO END =====
ERROR:root:Error while parsing file ../../TEST_1636586596_lsass.dmp
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/cmdhelper.py", line 195, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile)
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 77, in parse_minidump_file
    raise e
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 73, in parse_minidump_file
    mimi.start()
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 267, in start
    self.get_logoncreds()
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 168, in get_logoncreds
    logoncred_decryptor.start()
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/packages/msv/decryptor.py", line 360, in start
    entry_ptr_value, entry_ptr_loc = self.find_first_entry()
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/packages/msv/decryptor.py", line 263, in find_first_entry
    position = self.find_signature('lsasrv.dll',self.decryptor_template.signature)
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/package_commons.py", line 71, in find_signature
    raise Exception('Signature was not found in module %s Signature: %s' % (module_name, self.decryptor_template.signature.hex()))
Exception: Signature was not found in module lsasrv.dll Signature: 33ff4189374c8bf34585c074
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/cmdhelper.py", line 195, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile)
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 77, in parse_minidump_file
    raise e
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 73, in parse_minidump_file
    mimi.start()
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 267, in start
    self.get_logoncreds()
  File "/usr/lib/python3/dist-packages/pypykatz/pypykatz.py", line 168, in get_logoncreds
    logoncred_decryptor.start()
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/packages/msv/decryptor.py", line 360, in start
    entry_ptr_value, entry_ptr_loc = self.find_first_entry()
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/packages/msv/decryptor.py", line 263, in find_first_entry
    position = self.find_signature('lsasrv.dll',self.decryptor_template.signature)
  File "/usr/lib/python3/dist-packages/pypykatz/lsadecryptor/package_commons.py", line 71, in find_signature
    raise Exception('Signature was not found in module %s Signature: %s' % (module_name, self.decryptor_template.signature.hex()))
Exception: Signature was not found in module lsasrv.dll Signature: 33ff4189374c8bf34585c074
`

It was dumped fine but it could not be parsed either from mimikatz or pypykatz.

**Comment by S4ntiagoP** [comment]
Hey there!
did you run it with `-v`? if not, did you run `restore_signature.sh`?
Is the Windows machine 64 bit?

**Comment by trickster0** [comment]
Ye i tried it in 2 different hosts both ways -v and without and ran restore_signature.sh
Worth mentioning that both hosts were Windows 11 although i doubt it should have any difference at least on the syscalls calling.

**Comment by S4ntiagoP** [comment]
I don't have access to a W11 at this very moment but you could try to dump LSASS using the task manager or maybe by running `rundll32.exe C:\Windows\System32\comsvcs.dll MiniDump <lsass pid> lsass.dmp full` to confirm that pypykatz properly parses that dump.

**Comment by trickster0** [comment]
So I had an outdated pypykatz. Now it works! Good work man

**Comment by S4ntiagoP** [comment]
That is great! 😄 I'm glad
